#generated by model.py
from constants import *
def generate_features(state,action):
    s0,b0,a0=state.get_feature_context_window(action)
    feats=[]
    act_idx = state.model.class_codebook.get_index(action['type'])
    tx = action['tag'] if 'tag' in action else EMPTY
    s0_ne=s0['ne'] if s0 else EMPTY
    s0_w=s0['form'] if s0 else EMPTY
    s0_lemma=s0['lemma'] if s0 else EMPTY
    s0_t=s0['pos'] if s0 else EMPTY
    s0_dl=s0['rel'] if s0 else EMPTY
    s0_len=s0['len'] if s0 else EMPTY
    s0_txv=s0['txv'] if s0 else EMPTY
    s0_isnom=s0['isnom'] if s0 else EMPTY
    s0_nech=s0['nech'] if s0 else EMPTY
    s0_c1lemma=s0['c1lemma'] if s0 else EMPTY
    s0_c1dl=s0['c1dl'] if s0 else EMPTY
    s0_cpt=s0['concept'] if s0 else EMPTY
    s0_p1_ne=s0['p1']['ne'] if s0 and s0['p1'] else EMPTY
    b0_ne=b0['ne'] if b0 else EMPTY
    b0_w=b0['form'] if b0 else EMPTY
    b0_lemma=b0['lemma'] if b0 else EMPTY
    b0_t=b0['pos'] if b0 else EMPTY
    b0_dl=b0['rel'] if b0 else EMPTY
    b0_len=b0['len'] if b0 else EMPTY
    b0_reph=b0['reph'] if b0 else EMPTY
    a0_ne=a0['ne'] if a0 else EMPTY
    a0_w=a0['form'] if a0 else EMPTY
    a0_lemma=a0['lemma'] if a0 else EMPTY
    a0_t=a0['pos'] if a0 else EMPTY
    a0_dl=a0['rel'] if a0 else EMPTY
    s0_p1_w=s0['p1']['form'] if s0 and s0['p1'] else EMPTY
    s0_p1_lemma=s0['p1']['lemma'] if s0 and s0['p1'] else EMPTY
    s0_p1_t=s0['p1']['pos'] if s0 and s0['p1'] else EMPTY
    s0_p1_dl=s0['p1']['rel'] if s0 and s0['p1'] else EMPTY
    b0_pathpwd=b0['pathpwd'] if b0 else EMPTY
    b0_apathpwd=b0['apathpwd'] if b0 else EMPTY
    b0_rsb_dl=b0['rsb']['rel'] if b0 and b0['rsb'] else EMPTY
    b0_nswp=b0['nswp'] if b0 else EMPTY
    b0_pathp=b0['pathp'] if b0 else EMPTY
    b0_apathp=b0['apathp'] if b0 else EMPTY
    a0_cpt=a0['concept'] if a0 else EMPTY
    b0_cpt=b0['concept'] if b0 else EMPTY
    dist1=abs(s0['id']-b0['id']) if b0 and b0 is not ABT_TOKEN and s0 is not ABT_TOKEN else EMPTY
    if dist1 > 10: dist1=10
    dist2=abs(a0['id']-b0['id']) if b0 and a0 and b0 is not ABT_TOKEN and a0 is not ABT_TOKEN else EMPTY
    if dist2 > 10: dist2=10
    s_v0=WORD_VECS[s0['form']][0] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v1=WORD_VECS[s0['form']][1] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v2=WORD_VECS[s0['form']][2] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v3=WORD_VECS[s0['form']][3] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v4=WORD_VECS[s0['form']][4] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v5=WORD_VECS[s0['form']][5] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v6=WORD_VECS[s0['form']][6] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v7=WORD_VECS[s0['form']][7] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v8=WORD_VECS[s0['form']][8] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v9=WORD_VECS[s0['form']][9] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v10=WORD_VECS[s0['form']][10] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v11=WORD_VECS[s0['form']][11] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v12=WORD_VECS[s0['form']][12] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v13=WORD_VECS[s0['form']][13] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v14=WORD_VECS[s0['form']][14] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v15=WORD_VECS[s0['form']][15] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v16=WORD_VECS[s0['form']][16] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v17=WORD_VECS[s0['form']][17] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v18=WORD_VECS[s0['form']][18] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v19=WORD_VECS[s0['form']][19] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v20=WORD_VECS[s0['form']][20] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v21=WORD_VECS[s0['form']][21] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v22=WORD_VECS[s0['form']][22] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v23=WORD_VECS[s0['form']][23] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v24=WORD_VECS[s0['form']][24] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v25=WORD_VECS[s0['form']][25] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v26=WORD_VECS[s0['form']][26] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v27=WORD_VECS[s0['form']][27] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v28=WORD_VECS[s0['form']][28] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v29=WORD_VECS[s0['form']][29] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v30=WORD_VECS[s0['form']][30] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v31=WORD_VECS[s0['form']][31] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v32=WORD_VECS[s0['form']][32] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v33=WORD_VECS[s0['form']][33] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v34=WORD_VECS[s0['form']][34] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v35=WORD_VECS[s0['form']][35] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v36=WORD_VECS[s0['form']][36] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v37=WORD_VECS[s0['form']][37] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v38=WORD_VECS[s0['form']][38] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v39=WORD_VECS[s0['form']][39] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v40=WORD_VECS[s0['form']][40] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v41=WORD_VECS[s0['form']][41] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v42=WORD_VECS[s0['form']][42] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v43=WORD_VECS[s0['form']][43] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v44=WORD_VECS[s0['form']][44] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v45=WORD_VECS[s0['form']][45] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v46=WORD_VECS[s0['form']][46] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v47=WORD_VECS[s0['form']][47] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v48=WORD_VECS[s0['form']][48] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v49=WORD_VECS[s0['form']][49] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v50=WORD_VECS[s0['form']][50] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v51=WORD_VECS[s0['form']][51] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v52=WORD_VECS[s0['form']][52] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v53=WORD_VECS[s0['form']][53] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v54=WORD_VECS[s0['form']][54] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v55=WORD_VECS[s0['form']][55] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v56=WORD_VECS[s0['form']][56] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v57=WORD_VECS[s0['form']][57] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v58=WORD_VECS[s0['form']][58] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v59=WORD_VECS[s0['form']][59] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v60=WORD_VECS[s0['form']][60] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v61=WORD_VECS[s0['form']][61] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v62=WORD_VECS[s0['form']][62] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v63=WORD_VECS[s0['form']][63] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v64=WORD_VECS[s0['form']][64] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v65=WORD_VECS[s0['form']][65] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v66=WORD_VECS[s0['form']][66] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v67=WORD_VECS[s0['form']][67] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v68=WORD_VECS[s0['form']][68] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v69=WORD_VECS[s0['form']][69] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v70=WORD_VECS[s0['form']][70] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v71=WORD_VECS[s0['form']][71] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v72=WORD_VECS[s0['form']][72] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v73=WORD_VECS[s0['form']][73] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v74=WORD_VECS[s0['form']][74] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v75=WORD_VECS[s0['form']][75] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v76=WORD_VECS[s0['form']][76] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v77=WORD_VECS[s0['form']][77] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v78=WORD_VECS[s0['form']][78] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v79=WORD_VECS[s0['form']][79] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v80=WORD_VECS[s0['form']][80] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v81=WORD_VECS[s0['form']][81] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v82=WORD_VECS[s0['form']][82] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v83=WORD_VECS[s0['form']][83] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v84=WORD_VECS[s0['form']][84] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v85=WORD_VECS[s0['form']][85] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v86=WORD_VECS[s0['form']][86] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v87=WORD_VECS[s0['form']][87] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v88=WORD_VECS[s0['form']][88] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v89=WORD_VECS[s0['form']][89] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v90=WORD_VECS[s0['form']][90] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v91=WORD_VECS[s0['form']][91] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v92=WORD_VECS[s0['form']][92] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v93=WORD_VECS[s0['form']][93] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v94=WORD_VECS[s0['form']][94] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v95=WORD_VECS[s0['form']][95] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v96=WORD_VECS[s0['form']][96] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v97=WORD_VECS[s0['form']][97] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v98=WORD_VECS[s0['form']][98] if WORD_VECS[s0['form']] is not '' else EMPTY
    s_v99=WORD_VECS[s0['form']][99] if WORD_VECS[s0['form']] is not '' else EMPTY
    if s_v0 is not None: feats.append('s_v0=s_v0.format(0, 0)')
    if s_v1 is not None: feats.append('s_v1=s_v1.format(1, 1)')
    if s_v2 is not None: feats.append('s_v2=s_v2.format(2, 2)')
    if s_v3 is not None: feats.append('s_v3=s_v3.format(3, 3)')
    if s_v4 is not None: feats.append('s_v4=s_v4.format(4, 4)')
    if s_v5 is not None: feats.append('s_v5=s_v5.format(5, 5)')
    if s_v6 is not None: feats.append('s_v6=s_v6.format(6, 6)')
    if s_v7 is not None: feats.append('s_v7=s_v7.format(7, 7)')
    if s_v8 is not None: feats.append('s_v8=s_v8.format(8, 8)')
    if s_v9 is not None: feats.append('s_v9=s_v9.format(9, 9)')
    if s_v10 is not None: feats.append('s_v10=s_v10.format(10, 10)')
    if s_v11 is not None: feats.append('s_v11=s_v11.format(11, 11)')
    if s_v12 is not None: feats.append('s_v12=s_v12.format(12, 12)')
    if s_v13 is not None: feats.append('s_v13=s_v13.format(13, 13)')
    if s_v14 is not None: feats.append('s_v14=s_v14.format(14, 14)')
    if s_v15 is not None: feats.append('s_v15=s_v15.format(15, 15)')
    if s_v16 is not None: feats.append('s_v16=s_v16.format(16, 16)')
    if s_v17 is not None: feats.append('s_v17=s_v17.format(17, 17)')
    if s_v18 is not None: feats.append('s_v18=s_v18.format(18, 18)')
    if s_v19 is not None: feats.append('s_v19=s_v19.format(19, 19)')
    if s_v20 is not None: feats.append('s_v20=s_v20.format(20, 20)')
    if s_v21 is not None: feats.append('s_v21=s_v21.format(21, 21)')
    if s_v22 is not None: feats.append('s_v22=s_v22.format(22, 22)')
    if s_v23 is not None: feats.append('s_v23=s_v23.format(23, 23)')
    if s_v24 is not None: feats.append('s_v24=s_v24.format(24, 24)')
    if s_v25 is not None: feats.append('s_v25=s_v25.format(25, 25)')
    if s_v26 is not None: feats.append('s_v26=s_v26.format(26, 26)')
    if s_v27 is not None: feats.append('s_v27=s_v27.format(27, 27)')
    if s_v28 is not None: feats.append('s_v28=s_v28.format(28, 28)')
    if s_v29 is not None: feats.append('s_v29=s_v29.format(29, 29)')
    if s_v30 is not None: feats.append('s_v30=s_v30.format(30, 30)')
    if s_v31 is not None: feats.append('s_v31=s_v31.format(31, 31)')
    if s_v32 is not None: feats.append('s_v32=s_v32.format(32, 32)')
    if s_v33 is not None: feats.append('s_v33=s_v33.format(33, 33)')
    if s_v34 is not None: feats.append('s_v34=s_v34.format(34, 34)')
    if s_v35 is not None: feats.append('s_v35=s_v35.format(35, 35)')
    if s_v36 is not None: feats.append('s_v36=s_v36.format(36, 36)')
    if s_v37 is not None: feats.append('s_v37=s_v37.format(37, 37)')
    if s_v38 is not None: feats.append('s_v38=s_v38.format(38, 38)')
    if s_v39 is not None: feats.append('s_v39=s_v39.format(39, 39)')
    if s_v40 is not None: feats.append('s_v40=s_v40.format(40, 40)')
    if s_v41 is not None: feats.append('s_v41=s_v41.format(41, 41)')
    if s_v42 is not None: feats.append('s_v42=s_v42.format(42, 42)')
    if s_v43 is not None: feats.append('s_v43=s_v43.format(43, 43)')
    if s_v44 is not None: feats.append('s_v44=s_v44.format(44, 44)')
    if s_v45 is not None: feats.append('s_v45=s_v45.format(45, 45)')
    if s_v46 is not None: feats.append('s_v46=s_v46.format(46, 46)')
    if s_v47 is not None: feats.append('s_v47=s_v47.format(47, 47)')
    if s_v48 is not None: feats.append('s_v48=s_v48.format(48, 48)')
    if s_v49 is not None: feats.append('s_v49=s_v49.format(49, 49)')
    if s_v50 is not None: feats.append('s_v50=s_v50.format(50, 50)')
    if s_v51 is not None: feats.append('s_v51=s_v51.format(51, 51)')
    if s_v52 is not None: feats.append('s_v52=s_v52.format(52, 52)')
    if s_v53 is not None: feats.append('s_v53=s_v53.format(53, 53)')
    if s_v54 is not None: feats.append('s_v54=s_v54.format(54, 54)')
    if s_v55 is not None: feats.append('s_v55=s_v55.format(55, 55)')
    if s_v56 is not None: feats.append('s_v56=s_v56.format(56, 56)')
    if s_v57 is not None: feats.append('s_v57=s_v57.format(57, 57)')
    if s_v58 is not None: feats.append('s_v58=s_v58.format(58, 58)')
    if s_v59 is not None: feats.append('s_v59=s_v59.format(59, 59)')
    if s_v60 is not None: feats.append('s_v60=s_v60.format(60, 60)')
    if s_v61 is not None: feats.append('s_v61=s_v61.format(61, 61)')
    if s_v62 is not None: feats.append('s_v62=s_v62.format(62, 62)')
    if s_v63 is not None: feats.append('s_v63=s_v63.format(63, 63)')
    if s_v64 is not None: feats.append('s_v64=s_v64.format(64, 64)')
    if s_v65 is not None: feats.append('s_v65=s_v65.format(65, 65)')
    if s_v66 is not None: feats.append('s_v66=s_v66.format(66, 66)')
    if s_v67 is not None: feats.append('s_v67=s_v67.format(67, 67)')
    if s_v68 is not None: feats.append('s_v68=s_v68.format(68, 68)')
    if s_v69 is not None: feats.append('s_v69=s_v69.format(69, 69)')
    if s_v70 is not None: feats.append('s_v70=s_v70.format(70, 70)')
    if s_v71 is not None: feats.append('s_v71=s_v71.format(71, 71)')
    if s_v72 is not None: feats.append('s_v72=s_v72.format(72, 72)')
    if s_v73 is not None: feats.append('s_v73=s_v73.format(73, 73)')
    if s_v74 is not None: feats.append('s_v74=s_v74.format(74, 74)')
    if s_v75 is not None: feats.append('s_v75=s_v75.format(75, 75)')
    if s_v76 is not None: feats.append('s_v76=s_v76.format(76, 76)')
    if s_v77 is not None: feats.append('s_v77=s_v77.format(77, 77)')
    if s_v78 is not None: feats.append('s_v78=s_v78.format(78, 78)')
    if s_v79 is not None: feats.append('s_v79=s_v79.format(79, 79)')
    if s_v80 is not None: feats.append('s_v80=s_v80.format(80, 80)')
    if s_v81 is not None: feats.append('s_v81=s_v81.format(81, 81)')
    if s_v82 is not None: feats.append('s_v82=s_v82.format(82, 82)')
    if s_v83 is not None: feats.append('s_v83=s_v83.format(83, 83)')
    if s_v84 is not None: feats.append('s_v84=s_v84.format(84, 84)')
    if s_v85 is not None: feats.append('s_v85=s_v85.format(85, 85)')
    if s_v86 is not None: feats.append('s_v86=s_v86.format(86, 86)')
    if s_v87 is not None: feats.append('s_v87=s_v87.format(87, 87)')
    if s_v88 is not None: feats.append('s_v88=s_v88.format(88, 88)')
    if s_v89 is not None: feats.append('s_v89=s_v89.format(89, 89)')
    if s_v90 is not None: feats.append('s_v90=s_v90.format(90, 90)')
    if s_v91 is not None: feats.append('s_v91=s_v91.format(91, 91)')
    if s_v92 is not None: feats.append('s_v92=s_v92.format(92, 92)')
    if s_v93 is not None: feats.append('s_v93=s_v93.format(93, 93)')
    if s_v94 is not None: feats.append('s_v94=s_v94.format(94, 94)')
    if s_v95 is not None: feats.append('s_v95=s_v95.format(95, 95)')
    if s_v96 is not None: feats.append('s_v96=s_v96.format(96, 96)')
    if s_v97 is not None: feats.append('s_v97=s_v97.format(97, 97)')
    if s_v98 is not None: feats.append('s_v98=s_v98.format(98, 98)')
    if s_v99 is not None: feats.append('s_v99=s_v99.format(99, 99)')
    if [s0_ne,tx] != 2*[None]:feats.append('s0_ne&tx=%s_%s_' % (s0_ne,tx))
    if [s0_w,tx] != 2*[None]:feats.append('s0_w&tx=%s_%s_' % (s0_w,tx))
    if [s0_lemma,tx] != 2*[None]:feats.append('s0_lemma&tx=%s_%s_' % (s0_lemma,tx))
    if [s0_t,tx] != 2*[None]:feats.append('s0_t&tx=%s_%s_' % (s0_t,tx))
    if [s0_dl,tx] != 2*[None]:feats.append('s0_dl&tx=%s_%s_' % (s0_dl,tx))
    if [s0_len,tx] != 2*[None]:feats.append('s0_len&tx=%s_%s_' % (s0_len,tx))
    if [s0_t,s0_txv] != 2*[None]:feats.append('s0_t&s0_txv=%s_%s_' % (s0_t,s0_txv))
    if [s0_isnom] != 1*[None]:feats.append('s0_isnom=%s_' % (s0_isnom))
    if [s0_nech] != 1*[None]:feats.append('s0_nech=%s_' % (s0_nech))
    if [s0_lemma,s0_nech] != 2*[None]:feats.append('s0_lemma&s0_nech=%s_%s_' % (s0_lemma,s0_nech))
    if [s0_isnom,s0_nech] != 2*[None]:feats.append('s0_isnom&s0_nech=%s_%s_' % (s0_isnom,s0_nech))
    if [s0_c1lemma,tx] != 2*[None]:feats.append('s0_c1lemma&tx=%s_%s_' % (s0_c1lemma,tx))
    if [s0_c1dl,s0_c1lemma] != 2*[None]:feats.append('s0_c1dl&s0_c1lemma=%s_%s_' % (s0_c1dl,s0_c1lemma))
    if [s0_cpt,s0_p1_ne,s0_c1lemma] != 3*[None]:feats.append('s0_cpt&s0_p1_ne&s0_c1lemma=%s_%s_%s_' % (s0_cpt,s0_p1_ne,s0_c1lemma))
    if [b0_ne] != 1*[None]:feats.append('b0_ne=%s_' % (b0_ne))
    if [b0_w] != 1*[None]:feats.append('b0_w=%s_' % (b0_w))
    if [b0_lemma] != 1*[None]:feats.append('b0_lemma=%s_' % (b0_lemma))
    if [b0_t] != 1*[None]:feats.append('b0_t=%s_' % (b0_t))
    if [b0_dl] != 1*[None]:feats.append('b0_dl=%s_' % (b0_dl))
    if [b0_len] != 1*[None]:feats.append('b0_len=%s_' % (b0_len))
    if [b0_reph] != 1*[None]:feats.append('b0_reph=%s_' % (b0_reph))
    if [a0_ne] != 1*[None]:feats.append('a0_ne=%s_' % (a0_ne))
    if [a0_w] != 1*[None]:feats.append('a0_w=%s_' % (a0_w))
    if [a0_lemma] != 1*[None]:feats.append('a0_lemma=%s_' % (a0_lemma))
    if [a0_t] != 1*[None]:feats.append('a0_t=%s_' % (a0_t))
    if [a0_dl] != 1*[None]:feats.append('a0_dl=%s_' % (a0_dl))
    if [s0_p1_ne] != 1*[None]:feats.append('s0_p1_ne=%s_' % (s0_p1_ne))
    if [s0_p1_w] != 1*[None]:feats.append('s0_p1_w=%s_' % (s0_p1_w))
    if [s0_p1_lemma] != 1*[None]:feats.append('s0_p1_lemma=%s_' % (s0_p1_lemma))
    if [s0_p1_t] != 1*[None]:feats.append('s0_p1_t=%s_' % (s0_p1_t))
    if [s0_p1_dl] != 1*[None]:feats.append('s0_p1_dl=%s_' % (s0_p1_dl))
    if [b0_pathpwd,b0_lemma,s0_lemma] != 3*[None]:feats.append('b0_pathpwd&b0_lemma&s0_lemma=%s_%s_%s_' % (b0_pathpwd,b0_lemma,s0_lemma))
    if [b0_apathpwd,a0_lemma,b0_lemma] != 3*[None]:feats.append('b0_apathpwd&a0_lemma&b0_lemma=%s_%s_%s_' % (b0_apathpwd,a0_lemma,b0_lemma))
    if [b0_pathpwd] != 1*[None]:feats.append('b0_pathpwd=%s_' % (b0_pathpwd))
    if [b0_apathpwd] != 1*[None]:feats.append('b0_apathpwd=%s_' % (b0_apathpwd))
    if [b0_lemma,b0_rsb_dl] != 2*[None]:feats.append('b0_lemma&b0_rsb_dl=%s_%s_' % (b0_lemma,b0_rsb_dl))
    if [b0_lemma,b0_nswp] != 2*[None]:feats.append('b0_lemma&b0_nswp=%s_%s_' % (b0_lemma,b0_nswp))
    if [dist1] != 1*[None]:feats.append('dist1=%s_' % (dist1))
    if [dist1,b0_pathp] != 2*[None]:feats.append('dist1&b0_pathp=%s_%s_' % (dist1,b0_pathp))
    if [dist2] != 1*[None]:feats.append('dist2=%s_' % (dist2))
    if [dist2,b0_apathp] != 2*[None]:feats.append('dist2&b0_apathp=%s_%s_' % (dist2,b0_apathp))
    if [s0_lemma,b0_t] != 2*[None]:feats.append('s0_lemma&b0_t=%s_%s_' % (s0_lemma,b0_t))
    if [s0_lemma,b0_dl] != 2*[None]:feats.append('s0_lemma&b0_dl=%s_%s_' % (s0_lemma,b0_dl))
    if [s0_t,b0_lemma] != 2*[None]:feats.append('s0_t&b0_lemma=%s_%s_' % (s0_t,b0_lemma))
    if [s0_dl,b0_lemma] != 2*[None]:feats.append('s0_dl&b0_lemma=%s_%s_' % (s0_dl,b0_lemma))
    if [s0_ne,b0_ne] != 2*[None]:feats.append('s0_ne&b0_ne=%s_%s_' % (s0_ne,b0_ne))
    if [a0_t,b0_lemma] != 2*[None]:feats.append('a0_t&b0_lemma=%s_%s_' % (a0_t,b0_lemma))
    if [a0_dl,b0_lemma] != 2*[None]:feats.append('a0_dl&b0_lemma=%s_%s_' % (a0_dl,b0_lemma))
    if [a0_ne,b0_ne] != 2*[None]:feats.append('a0_ne&b0_ne=%s_%s_' % (a0_ne,b0_ne))
    if [a0_cpt,b0_cpt] != 2*[None]:feats.append('a0_cpt&b0_cpt=%s_%s_' % (a0_cpt,b0_cpt))
    if [a0_cpt,b0_cpt,s0_lemma] != 3*[None]:feats.append('a0_cpt&b0_cpt&s0_lemma=%s_%s_%s_' % (a0_cpt,b0_cpt,s0_lemma))
    if [a0_cpt,b0_ne] != 2*[None]:feats.append('a0_cpt&b0_ne=%s_%s_' % (a0_cpt,b0_ne))
    return feats