#generated by model.py
from constants import *
def generate_features(state,action):
    s0,b0,a0=state.get_feature_context_window(action)
    feats=[]
    act_idx = state.model.class_codebook.get_index(action['type'])
    tx = action['tag'] if 'tag' in action else EMPTY
    s0_v0=s0['v0'] if s0 else EMPTY
    s0_v1=s0['v1'] if s0 else EMPTY
    s0_v2=s0['v2'] if s0 else EMPTY
    s0_v3=s0['v3'] if s0 else EMPTY
    s0_v4=s0['v4'] if s0 else EMPTY
    s0_v5=s0['v5'] if s0 else EMPTY
    s0_v6=s0['v6'] if s0 else EMPTY
    s0_v7=s0['v7'] if s0 else EMPTY
    s0_v8=s0['v8'] if s0 else EMPTY
    s0_v9=s0['v9'] if s0 else EMPTY
    s0_v10=s0['v10'] if s0 else EMPTY
    s0_v11=s0['v11'] if s0 else EMPTY
    s0_v12=s0['v12'] if s0 else EMPTY
    s0_v13=s0['v13'] if s0 else EMPTY
    s0_v14=s0['v14'] if s0 else EMPTY
    s0_v15=s0['v15'] if s0 else EMPTY
    s0_v16=s0['v16'] if s0 else EMPTY
    s0_v17=s0['v17'] if s0 else EMPTY
    s0_v18=s0['v18'] if s0 else EMPTY
    s0_v19=s0['v19'] if s0 else EMPTY
    s0_v20=s0['v20'] if s0 else EMPTY
    s0_v21=s0['v21'] if s0 else EMPTY
    s0_v22=s0['v22'] if s0 else EMPTY
    s0_v23=s0['v23'] if s0 else EMPTY
    s0_v24=s0['v24'] if s0 else EMPTY
    s0_v25=s0['v25'] if s0 else EMPTY
    s0_v26=s0['v26'] if s0 else EMPTY
    s0_v27=s0['v27'] if s0 else EMPTY
    s0_v28=s0['v28'] if s0 else EMPTY
    s0_v29=s0['v29'] if s0 else EMPTY
    s0_v30=s0['v30'] if s0 else EMPTY
    s0_v31=s0['v31'] if s0 else EMPTY
    s0_v32=s0['v32'] if s0 else EMPTY
    s0_v33=s0['v33'] if s0 else EMPTY
    s0_v34=s0['v34'] if s0 else EMPTY
    s0_v35=s0['v35'] if s0 else EMPTY
    s0_v36=s0['v36'] if s0 else EMPTY
    s0_v37=s0['v37'] if s0 else EMPTY
    s0_v38=s0['v38'] if s0 else EMPTY
    s0_v39=s0['v39'] if s0 else EMPTY
    s0_v40=s0['v40'] if s0 else EMPTY
    s0_v41=s0['v41'] if s0 else EMPTY
    s0_v42=s0['v42'] if s0 else EMPTY
    s0_v43=s0['v43'] if s0 else EMPTY
    s0_v44=s0['v44'] if s0 else EMPTY
    s0_v45=s0['v45'] if s0 else EMPTY
    s0_v46=s0['v46'] if s0 else EMPTY
    s0_v47=s0['v47'] if s0 else EMPTY
    s0_v48=s0['v48'] if s0 else EMPTY
    s0_v49=s0['v49'] if s0 else EMPTY
    b0_v0=b0['v0'] if b0 else EMPTY
    b0_v1=b0['v1'] if b0 else EMPTY
    b0_v2=b0['v2'] if b0 else EMPTY
    b0_v3=b0['v3'] if b0 else EMPTY
    b0_v4=b0['v4'] if b0 else EMPTY
    b0_v5=b0['v5'] if b0 else EMPTY
    b0_v6=b0['v6'] if b0 else EMPTY
    b0_v7=b0['v7'] if b0 else EMPTY
    b0_v8=b0['v8'] if b0 else EMPTY
    b0_v9=b0['v9'] if b0 else EMPTY
    b0_v10=b0['v10'] if b0 else EMPTY
    b0_v11=b0['v11'] if b0 else EMPTY
    b0_v12=b0['v12'] if b0 else EMPTY
    b0_v13=b0['v13'] if b0 else EMPTY
    b0_v14=b0['v14'] if b0 else EMPTY
    b0_v15=b0['v15'] if b0 else EMPTY
    b0_v16=b0['v16'] if b0 else EMPTY
    b0_v17=b0['v17'] if b0 else EMPTY
    b0_v18=b0['v18'] if b0 else EMPTY
    b0_v19=b0['v19'] if b0 else EMPTY
    b0_v20=b0['v20'] if b0 else EMPTY
    b0_v21=b0['v21'] if b0 else EMPTY
    b0_v22=b0['v22'] if b0 else EMPTY
    b0_v23=b0['v23'] if b0 else EMPTY
    b0_v24=b0['v24'] if b0 else EMPTY
    b0_v25=b0['v25'] if b0 else EMPTY
    b0_v26=b0['v26'] if b0 else EMPTY
    b0_v27=b0['v27'] if b0 else EMPTY
    b0_v28=b0['v28'] if b0 else EMPTY
    b0_v29=b0['v29'] if b0 else EMPTY
    b0_v30=b0['v30'] if b0 else EMPTY
    b0_v31=b0['v31'] if b0 else EMPTY
    b0_v32=b0['v32'] if b0 else EMPTY
    b0_v33=b0['v33'] if b0 else EMPTY
    b0_v34=b0['v34'] if b0 else EMPTY
    b0_v35=b0['v35'] if b0 else EMPTY
    b0_v36=b0['v36'] if b0 else EMPTY
    b0_v37=b0['v37'] if b0 else EMPTY
    b0_v38=b0['v38'] if b0 else EMPTY
    b0_v39=b0['v39'] if b0 else EMPTY
    b0_v40=b0['v40'] if b0 else EMPTY
    b0_v41=b0['v41'] if b0 else EMPTY
    b0_v42=b0['v42'] if b0 else EMPTY
    b0_v43=b0['v43'] if b0 else EMPTY
    b0_v44=b0['v44'] if b0 else EMPTY
    b0_v45=b0['v45'] if b0 else EMPTY
    b0_v46=b0['v46'] if b0 else EMPTY
    b0_v47=b0['v47'] if b0 else EMPTY
    b0_v48=b0['v48'] if b0 else EMPTY
    b0_v49=b0['v49'] if b0 else EMPTY
    dist1=abs(s0['id']-b0['id']) if b0 and b0 is not ABT_TOKEN and s0 is not ABT_TOKEN else EMPTY
    if dist1 > 10: dist1=10
    dist2=abs(a0['id']-b0['id']) if b0 and a0 and b0 is not ABT_TOKEN and a0 is not ABT_TOKEN else EMPTY
    if dist2 > 10: dist2=10
    if [s0_v0,tx] != 2*[None]:feats.append('s0_v0&tx=%s_%s_' % (s0_v0,tx))
    if [s0_v1,tx] != 2*[None]:feats.append('s0_v1&tx=%s_%s_' % (s0_v1,tx))
    if [s0_v2,tx] != 2*[None]:feats.append('s0_v2&tx=%s_%s_' % (s0_v2,tx))
    if [s0_v3,tx] != 2*[None]:feats.append('s0_v3&tx=%s_%s_' % (s0_v3,tx))
    if [s0_v4,tx] != 2*[None]:feats.append('s0_v4&tx=%s_%s_' % (s0_v4,tx))
    if [s0_v5,tx] != 2*[None]:feats.append('s0_v5&tx=%s_%s_' % (s0_v5,tx))
    if [s0_v6,tx] != 2*[None]:feats.append('s0_v6&tx=%s_%s_' % (s0_v6,tx))
    if [s0_v7,tx] != 2*[None]:feats.append('s0_v7&tx=%s_%s_' % (s0_v7,tx))
    if [s0_v8,tx] != 2*[None]:feats.append('s0_v8&tx=%s_%s_' % (s0_v8,tx))
    if [s0_v9,tx] != 2*[None]:feats.append('s0_v9&tx=%s_%s_' % (s0_v9,tx))
    if [s0_v10,tx] != 2*[None]:feats.append('s0_v10&tx=%s_%s_' % (s0_v10,tx))
    if [s0_v11,tx] != 2*[None]:feats.append('s0_v11&tx=%s_%s_' % (s0_v11,tx))
    if [s0_v12,tx] != 2*[None]:feats.append('s0_v12&tx=%s_%s_' % (s0_v12,tx))
    if [s0_v13,tx] != 2*[None]:feats.append('s0_v13&tx=%s_%s_' % (s0_v13,tx))
    if [s0_v14,tx] != 2*[None]:feats.append('s0_v14&tx=%s_%s_' % (s0_v14,tx))
    if [s0_v15,tx] != 2*[None]:feats.append('s0_v15&tx=%s_%s_' % (s0_v15,tx))
    if [s0_v16,tx] != 2*[None]:feats.append('s0_v16&tx=%s_%s_' % (s0_v16,tx))
    if [s0_v17,tx] != 2*[None]:feats.append('s0_v17&tx=%s_%s_' % (s0_v17,tx))
    if [s0_v18,tx] != 2*[None]:feats.append('s0_v18&tx=%s_%s_' % (s0_v18,tx))
    if [s0_v19,tx] != 2*[None]:feats.append('s0_v19&tx=%s_%s_' % (s0_v19,tx))
    if [s0_v20,tx] != 2*[None]:feats.append('s0_v20&tx=%s_%s_' % (s0_v20,tx))
    if [s0_v21,tx] != 2*[None]:feats.append('s0_v21&tx=%s_%s_' % (s0_v21,tx))
    if [s0_v22,tx] != 2*[None]:feats.append('s0_v22&tx=%s_%s_' % (s0_v22,tx))
    if [s0_v23,tx] != 2*[None]:feats.append('s0_v23&tx=%s_%s_' % (s0_v23,tx))
    if [s0_v24,tx] != 2*[None]:feats.append('s0_v24&tx=%s_%s_' % (s0_v24,tx))
    if [s0_v25,tx] != 2*[None]:feats.append('s0_v25&tx=%s_%s_' % (s0_v25,tx))
    if [s0_v26,tx] != 2*[None]:feats.append('s0_v26&tx=%s_%s_' % (s0_v26,tx))
    if [s0_v27,tx] != 2*[None]:feats.append('s0_v27&tx=%s_%s_' % (s0_v27,tx))
    if [s0_v28,tx] != 2*[None]:feats.append('s0_v28&tx=%s_%s_' % (s0_v28,tx))
    if [s0_v29,tx] != 2*[None]:feats.append('s0_v29&tx=%s_%s_' % (s0_v29,tx))
    if [s0_v30,tx] != 2*[None]:feats.append('s0_v30&tx=%s_%s_' % (s0_v30,tx))
    if [s0_v31,tx] != 2*[None]:feats.append('s0_v31&tx=%s_%s_' % (s0_v31,tx))
    if [s0_v32,tx] != 2*[None]:feats.append('s0_v32&tx=%s_%s_' % (s0_v32,tx))
    if [s0_v33,tx] != 2*[None]:feats.append('s0_v33&tx=%s_%s_' % (s0_v33,tx))
    if [s0_v34,tx] != 2*[None]:feats.append('s0_v34&tx=%s_%s_' % (s0_v34,tx))
    if [s0_v35,tx] != 2*[None]:feats.append('s0_v35&tx=%s_%s_' % (s0_v35,tx))
    if [s0_v36,tx] != 2*[None]:feats.append('s0_v36&tx=%s_%s_' % (s0_v36,tx))
    if [s0_v37,tx] != 2*[None]:feats.append('s0_v37&tx=%s_%s_' % (s0_v37,tx))
    if [s0_v38,tx] != 2*[None]:feats.append('s0_v38&tx=%s_%s_' % (s0_v38,tx))
    if [s0_v39,tx] != 2*[None]:feats.append('s0_v39&tx=%s_%s_' % (s0_v39,tx))
    if [s0_v40,tx] != 2*[None]:feats.append('s0_v40&tx=%s_%s_' % (s0_v40,tx))
    if [s0_v41,tx] != 2*[None]:feats.append('s0_v41&tx=%s_%s_' % (s0_v41,tx))
    if [s0_v42,tx] != 2*[None]:feats.append('s0_v42&tx=%s_%s_' % (s0_v42,tx))
    if [s0_v43,tx] != 2*[None]:feats.append('s0_v43&tx=%s_%s_' % (s0_v43,tx))
    if [s0_v44,tx] != 2*[None]:feats.append('s0_v44&tx=%s_%s_' % (s0_v44,tx))
    if [s0_v45,tx] != 2*[None]:feats.append('s0_v45&tx=%s_%s_' % (s0_v45,tx))
    if [s0_v46,tx] != 2*[None]:feats.append('s0_v46&tx=%s_%s_' % (s0_v46,tx))
    if [s0_v47,tx] != 2*[None]:feats.append('s0_v47&tx=%s_%s_' % (s0_v47,tx))
    if [s0_v48,tx] != 2*[None]:feats.append('s0_v48&tx=%s_%s_' % (s0_v48,tx))
    if [s0_v49,tx] != 2*[None]:feats.append('s0_v49&tx=%s_%s_' % (s0_v49,tx))
    if [s0_v0] != 1*[None]:feats.append('s0_v0=%s_' % (s0_v0))
    if [s0_v1] != 1*[None]:feats.append('s0_v1=%s_' % (s0_v1))
    if [s0_v2] != 1*[None]:feats.append('s0_v2=%s_' % (s0_v2))
    if [s0_v3] != 1*[None]:feats.append('s0_v3=%s_' % (s0_v3))
    if [s0_v4] != 1*[None]:feats.append('s0_v4=%s_' % (s0_v4))
    if [s0_v5] != 1*[None]:feats.append('s0_v5=%s_' % (s0_v5))
    if [s0_v6] != 1*[None]:feats.append('s0_v6=%s_' % (s0_v6))
    if [s0_v7] != 1*[None]:feats.append('s0_v7=%s_' % (s0_v7))
    if [s0_v8] != 1*[None]:feats.append('s0_v8=%s_' % (s0_v8))
    if [s0_v9] != 1*[None]:feats.append('s0_v9=%s_' % (s0_v9))
    if [s0_v10] != 1*[None]:feats.append('s0_v10=%s_' % (s0_v10))
    if [s0_v11] != 1*[None]:feats.append('s0_v11=%s_' % (s0_v11))
    if [s0_v12] != 1*[None]:feats.append('s0_v12=%s_' % (s0_v12))
    if [s0_v13] != 1*[None]:feats.append('s0_v13=%s_' % (s0_v13))
    if [s0_v14] != 1*[None]:feats.append('s0_v14=%s_' % (s0_v14))
    if [s0_v15] != 1*[None]:feats.append('s0_v15=%s_' % (s0_v15))
    if [s0_v16] != 1*[None]:feats.append('s0_v16=%s_' % (s0_v16))
    if [s0_v17] != 1*[None]:feats.append('s0_v17=%s_' % (s0_v17))
    if [s0_v18] != 1*[None]:feats.append('s0_v18=%s_' % (s0_v18))
    if [s0_v19] != 1*[None]:feats.append('s0_v19=%s_' % (s0_v19))
    if [s0_v20] != 1*[None]:feats.append('s0_v20=%s_' % (s0_v20))
    if [s0_v21] != 1*[None]:feats.append('s0_v21=%s_' % (s0_v21))
    if [s0_v22] != 1*[None]:feats.append('s0_v22=%s_' % (s0_v22))
    if [s0_v23] != 1*[None]:feats.append('s0_v23=%s_' % (s0_v23))
    if [s0_v24] != 1*[None]:feats.append('s0_v24=%s_' % (s0_v24))
    if [s0_v25] != 1*[None]:feats.append('s0_v25=%s_' % (s0_v25))
    if [s0_v26] != 1*[None]:feats.append('s0_v26=%s_' % (s0_v26))
    if [s0_v27] != 1*[None]:feats.append('s0_v27=%s_' % (s0_v27))
    if [s0_v28] != 1*[None]:feats.append('s0_v28=%s_' % (s0_v28))
    if [s0_v29] != 1*[None]:feats.append('s0_v29=%s_' % (s0_v29))
    if [s0_v30] != 1*[None]:feats.append('s0_v30=%s_' % (s0_v30))
    if [s0_v31] != 1*[None]:feats.append('s0_v31=%s_' % (s0_v31))
    if [s0_v32] != 1*[None]:feats.append('s0_v32=%s_' % (s0_v32))
    if [s0_v33] != 1*[None]:feats.append('s0_v33=%s_' % (s0_v33))
    if [s0_v34] != 1*[None]:feats.append('s0_v34=%s_' % (s0_v34))
    if [s0_v35] != 1*[None]:feats.append('s0_v35=%s_' % (s0_v35))
    if [s0_v36] != 1*[None]:feats.append('s0_v36=%s_' % (s0_v36))
    if [s0_v37] != 1*[None]:feats.append('s0_v37=%s_' % (s0_v37))
    if [s0_v38] != 1*[None]:feats.append('s0_v38=%s_' % (s0_v38))
    if [s0_v39] != 1*[None]:feats.append('s0_v39=%s_' % (s0_v39))
    if [s0_v40] != 1*[None]:feats.append('s0_v40=%s_' % (s0_v40))
    if [s0_v41] != 1*[None]:feats.append('s0_v41=%s_' % (s0_v41))
    if [s0_v42] != 1*[None]:feats.append('s0_v42=%s_' % (s0_v42))
    if [s0_v43] != 1*[None]:feats.append('s0_v43=%s_' % (s0_v43))
    if [s0_v44] != 1*[None]:feats.append('s0_v44=%s_' % (s0_v44))
    if [s0_v45] != 1*[None]:feats.append('s0_v45=%s_' % (s0_v45))
    if [s0_v46] != 1*[None]:feats.append('s0_v46=%s_' % (s0_v46))
    if [s0_v47] != 1*[None]:feats.append('s0_v47=%s_' % (s0_v47))
    if [s0_v48] != 1*[None]:feats.append('s0_v48=%s_' % (s0_v48))
    if [s0_v49] != 1*[None]:feats.append('s0_v49=%s_' % (s0_v49))
    if [b0_v0] != 1*[None]:feats.append('b0_v0=%s_' % (b0_v0))
    if [b0_v1] != 1*[None]:feats.append('b0_v1=%s_' % (b0_v1))
    if [b0_v2] != 1*[None]:feats.append('b0_v2=%s_' % (b0_v2))
    if [b0_v3] != 1*[None]:feats.append('b0_v3=%s_' % (b0_v3))
    if [b0_v4] != 1*[None]:feats.append('b0_v4=%s_' % (b0_v4))
    if [b0_v5] != 1*[None]:feats.append('b0_v5=%s_' % (b0_v5))
    if [b0_v6] != 1*[None]:feats.append('b0_v6=%s_' % (b0_v6))
    if [b0_v7] != 1*[None]:feats.append('b0_v7=%s_' % (b0_v7))
    if [b0_v8] != 1*[None]:feats.append('b0_v8=%s_' % (b0_v8))
    if [b0_v9] != 1*[None]:feats.append('b0_v9=%s_' % (b0_v9))
    if [b0_v10] != 1*[None]:feats.append('b0_v10=%s_' % (b0_v10))
    if [b0_v11] != 1*[None]:feats.append('b0_v11=%s_' % (b0_v11))
    if [b0_v12] != 1*[None]:feats.append('b0_v12=%s_' % (b0_v12))
    if [b0_v13] != 1*[None]:feats.append('b0_v13=%s_' % (b0_v13))
    if [b0_v14] != 1*[None]:feats.append('b0_v14=%s_' % (b0_v14))
    if [b0_v15] != 1*[None]:feats.append('b0_v15=%s_' % (b0_v15))
    if [b0_v16] != 1*[None]:feats.append('b0_v16=%s_' % (b0_v16))
    if [b0_v17] != 1*[None]:feats.append('b0_v17=%s_' % (b0_v17))
    if [b0_v18] != 1*[None]:feats.append('b0_v18=%s_' % (b0_v18))
    if [b0_v19] != 1*[None]:feats.append('b0_v19=%s_' % (b0_v19))
    if [b0_v20] != 1*[None]:feats.append('b0_v20=%s_' % (b0_v20))
    if [b0_v21] != 1*[None]:feats.append('b0_v21=%s_' % (b0_v21))
    if [b0_v22] != 1*[None]:feats.append('b0_v22=%s_' % (b0_v22))
    if [b0_v23] != 1*[None]:feats.append('b0_v23=%s_' % (b0_v23))
    if [b0_v24] != 1*[None]:feats.append('b0_v24=%s_' % (b0_v24))
    if [b0_v25] != 1*[None]:feats.append('b0_v25=%s_' % (b0_v25))
    if [b0_v26] != 1*[None]:feats.append('b0_v26=%s_' % (b0_v26))
    if [b0_v27] != 1*[None]:feats.append('b0_v27=%s_' % (b0_v27))
    if [b0_v28] != 1*[None]:feats.append('b0_v28=%s_' % (b0_v28))
    if [b0_v29] != 1*[None]:feats.append('b0_v29=%s_' % (b0_v29))
    if [b0_v30] != 1*[None]:feats.append('b0_v30=%s_' % (b0_v30))
    if [b0_v31] != 1*[None]:feats.append('b0_v31=%s_' % (b0_v31))
    if [b0_v32] != 1*[None]:feats.append('b0_v32=%s_' % (b0_v32))
    if [b0_v33] != 1*[None]:feats.append('b0_v33=%s_' % (b0_v33))
    if [b0_v34] != 1*[None]:feats.append('b0_v34=%s_' % (b0_v34))
    if [b0_v35] != 1*[None]:feats.append('b0_v35=%s_' % (b0_v35))
    if [b0_v36] != 1*[None]:feats.append('b0_v36=%s_' % (b0_v36))
    if [b0_v37] != 1*[None]:feats.append('b0_v37=%s_' % (b0_v37))
    if [b0_v38] != 1*[None]:feats.append('b0_v38=%s_' % (b0_v38))
    if [b0_v39] != 1*[None]:feats.append('b0_v39=%s_' % (b0_v39))
    if [b0_v40] != 1*[None]:feats.append('b0_v40=%s_' % (b0_v40))
    if [b0_v41] != 1*[None]:feats.append('b0_v41=%s_' % (b0_v41))
    if [b0_v42] != 1*[None]:feats.append('b0_v42=%s_' % (b0_v42))
    if [b0_v43] != 1*[None]:feats.append('b0_v43=%s_' % (b0_v43))
    if [b0_v44] != 1*[None]:feats.append('b0_v44=%s_' % (b0_v44))
    if [b0_v45] != 1*[None]:feats.append('b0_v45=%s_' % (b0_v45))
    if [b0_v46] != 1*[None]:feats.append('b0_v46=%s_' % (b0_v46))
    if [b0_v47] != 1*[None]:feats.append('b0_v47=%s_' % (b0_v47))
    if [b0_v48] != 1*[None]:feats.append('b0_v48=%s_' % (b0_v48))
    if [b0_v49] != 1*[None]:feats.append('b0_v49=%s_' % (b0_v49))
    return feats