#generated by model.py
from constants import *
def generate_features(state,action):
    s0,b0,a0=state.get_feature_context_window(action)
    feats=[]
    act_idx = state.model.class_codebook.get_index(action['type'])
    tx = action['tag'] if 'tag' in action else EMPTY
    s0_ne=s0['ne'] if s0 else EMPTY
    s0_w=s0['form'] if s0 else EMPTY
    s0_lemma=s0['lemma'] if s0 else EMPTY
    s0_t=s0['pos'] if s0 else EMPTY
    s0_dl=s0['rel'] if s0 else EMPTY
    s0_len=s0['len'] if s0 else EMPTY
    s0_v0=s0['v0'] if s0 else EMPTY
    s0_v1=s0['v1'] if s0 else EMPTY
    s0_v2=s0['v2'] if s0 else EMPTY
    s0_v3=s0['v3'] if s0 else EMPTY
    s0_v4=s0['v4'] if s0 else EMPTY
    s0_v5=s0['v5'] if s0 else EMPTY
    s0_v6=s0['v6'] if s0 else EMPTY
    s0_v7=s0['v7'] if s0 else EMPTY
    s0_v8=s0['v8'] if s0 else EMPTY
    s0_v9=s0['v9'] if s0 else EMPTY
    s0_v10=s0['v10'] if s0 else EMPTY
    s0_v11=s0['v11'] if s0 else EMPTY
    s0_v12=s0['v12'] if s0 else EMPTY
    s0_v13=s0['v13'] if s0 else EMPTY
    s0_v14=s0['v14'] if s0 else EMPTY
    s0_v15=s0['v15'] if s0 else EMPTY
    s0_v16=s0['v16'] if s0 else EMPTY
    s0_v17=s0['v17'] if s0 else EMPTY
    s0_v18=s0['v18'] if s0 else EMPTY
    s0_v19=s0['v19'] if s0 else EMPTY
    s0_v20=s0['v20'] if s0 else EMPTY
    s0_v21=s0['v21'] if s0 else EMPTY
    s0_v22=s0['v22'] if s0 else EMPTY
    s0_v23=s0['v23'] if s0 else EMPTY
    s0_v24=s0['v24'] if s0 else EMPTY
    s0_v25=s0['v25'] if s0 else EMPTY
    s0_v26=s0['v26'] if s0 else EMPTY
    s0_v27=s0['v27'] if s0 else EMPTY
    s0_v28=s0['v28'] if s0 else EMPTY
    s0_v29=s0['v29'] if s0 else EMPTY
    s0_v30=s0['v30'] if s0 else EMPTY
    s0_v31=s0['v31'] if s0 else EMPTY
    s0_v32=s0['v32'] if s0 else EMPTY
    s0_v33=s0['v33'] if s0 else EMPTY
    s0_v34=s0['v34'] if s0 else EMPTY
    s0_v35=s0['v35'] if s0 else EMPTY
    s0_v36=s0['v36'] if s0 else EMPTY
    s0_v37=s0['v37'] if s0 else EMPTY
    s0_v38=s0['v38'] if s0 else EMPTY
    s0_v39=s0['v39'] if s0 else EMPTY
    s0_v40=s0['v40'] if s0 else EMPTY
    s0_v41=s0['v41'] if s0 else EMPTY
    s0_v42=s0['v42'] if s0 else EMPTY
    s0_v43=s0['v43'] if s0 else EMPTY
    s0_v44=s0['v44'] if s0 else EMPTY
    s0_v45=s0['v45'] if s0 else EMPTY
    s0_v46=s0['v46'] if s0 else EMPTY
    s0_v47=s0['v47'] if s0 else EMPTY
    s0_v48=s0['v48'] if s0 else EMPTY
    s0_v49=s0['v49'] if s0 else EMPTY
    s0_v50=s0['v50'] if s0 else EMPTY
    s0_v51=s0['v51'] if s0 else EMPTY
    s0_v52=s0['v52'] if s0 else EMPTY
    s0_v53=s0['v53'] if s0 else EMPTY
    s0_v54=s0['v54'] if s0 else EMPTY
    s0_v55=s0['v55'] if s0 else EMPTY
    s0_v56=s0['v56'] if s0 else EMPTY
    s0_v57=s0['v57'] if s0 else EMPTY
    s0_v58=s0['v58'] if s0 else EMPTY
    s0_v59=s0['v59'] if s0 else EMPTY
    s0_v60=s0['v60'] if s0 else EMPTY
    s0_v61=s0['v61'] if s0 else EMPTY
    s0_v62=s0['v62'] if s0 else EMPTY
    s0_v63=s0['v63'] if s0 else EMPTY
    s0_v64=s0['v64'] if s0 else EMPTY
    s0_v65=s0['v65'] if s0 else EMPTY
    s0_v66=s0['v66'] if s0 else EMPTY
    s0_v67=s0['v67'] if s0 else EMPTY
    s0_v68=s0['v68'] if s0 else EMPTY
    s0_v69=s0['v69'] if s0 else EMPTY
    s0_v70=s0['v70'] if s0 else EMPTY
    s0_v71=s0['v71'] if s0 else EMPTY
    s0_v72=s0['v72'] if s0 else EMPTY
    s0_v73=s0['v73'] if s0 else EMPTY
    s0_v74=s0['v74'] if s0 else EMPTY
    s0_v75=s0['v75'] if s0 else EMPTY
    s0_v76=s0['v76'] if s0 else EMPTY
    s0_v77=s0['v77'] if s0 else EMPTY
    s0_v78=s0['v78'] if s0 else EMPTY
    s0_v79=s0['v79'] if s0 else EMPTY
    s0_v80=s0['v80'] if s0 else EMPTY
    s0_v81=s0['v81'] if s0 else EMPTY
    s0_v82=s0['v82'] if s0 else EMPTY
    s0_v83=s0['v83'] if s0 else EMPTY
    s0_v84=s0['v84'] if s0 else EMPTY
    s0_v85=s0['v85'] if s0 else EMPTY
    s0_v86=s0['v86'] if s0 else EMPTY
    s0_v87=s0['v87'] if s0 else EMPTY
    s0_v88=s0['v88'] if s0 else EMPTY
    s0_v89=s0['v89'] if s0 else EMPTY
    s0_v90=s0['v90'] if s0 else EMPTY
    s0_v91=s0['v91'] if s0 else EMPTY
    s0_v92=s0['v92'] if s0 else EMPTY
    s0_v93=s0['v93'] if s0 else EMPTY
    s0_v94=s0['v94'] if s0 else EMPTY
    s0_v95=s0['v95'] if s0 else EMPTY
    s0_v96=s0['v96'] if s0 else EMPTY
    s0_v97=s0['v97'] if s0 else EMPTY
    s0_v98=s0['v98'] if s0 else EMPTY
    s0_v99=s0['v99'] if s0 else EMPTY
    b0_ne=b0['ne'] if b0 else EMPTY
    b0_w=b0['form'] if b0 else EMPTY
    b0_lemma=b0['lemma'] if b0 else EMPTY
    b0_t=b0['pos'] if b0 else EMPTY
    b0_dl=b0['rel'] if b0 else EMPTY
    b0_len=b0['len'] if b0 else EMPTY
    b0_reph=b0['reph'] if b0 else EMPTY
    b0_v0=b0['v0'] if b0 else EMPTY
    b0_v1=b0['v1'] if b0 else EMPTY
    b0_v2=b0['v2'] if b0 else EMPTY
    b0_v3=b0['v3'] if b0 else EMPTY
    b0_v4=b0['v4'] if b0 else EMPTY
    b0_v5=b0['v5'] if b0 else EMPTY
    b0_v6=b0['v6'] if b0 else EMPTY
    b0_v7=b0['v7'] if b0 else EMPTY
    b0_v8=b0['v8'] if b0 else EMPTY
    b0_v9=b0['v9'] if b0 else EMPTY
    b0_v10=b0['v10'] if b0 else EMPTY
    b0_v11=b0['v11'] if b0 else EMPTY
    b0_v12=b0['v12'] if b0 else EMPTY
    b0_v13=b0['v13'] if b0 else EMPTY
    b0_v14=b0['v14'] if b0 else EMPTY
    b0_v15=b0['v15'] if b0 else EMPTY
    b0_v16=b0['v16'] if b0 else EMPTY
    b0_v17=b0['v17'] if b0 else EMPTY
    b0_v18=b0['v18'] if b0 else EMPTY
    b0_v19=b0['v19'] if b0 else EMPTY
    b0_v20=b0['v20'] if b0 else EMPTY
    b0_v21=b0['v21'] if b0 else EMPTY
    b0_v22=b0['v22'] if b0 else EMPTY
    b0_v23=b0['v23'] if b0 else EMPTY
    b0_v24=b0['v24'] if b0 else EMPTY
    b0_v25=b0['v25'] if b0 else EMPTY
    b0_v26=b0['v26'] if b0 else EMPTY
    b0_v27=b0['v27'] if b0 else EMPTY
    b0_v28=b0['v28'] if b0 else EMPTY
    b0_v29=b0['v29'] if b0 else EMPTY
    b0_v30=b0['v30'] if b0 else EMPTY
    b0_v31=b0['v31'] if b0 else EMPTY
    b0_v32=b0['v32'] if b0 else EMPTY
    b0_v33=b0['v33'] if b0 else EMPTY
    b0_v34=b0['v34'] if b0 else EMPTY
    b0_v35=b0['v35'] if b0 else EMPTY
    b0_v36=b0['v36'] if b0 else EMPTY
    b0_v37=b0['v37'] if b0 else EMPTY
    b0_v38=b0['v38'] if b0 else EMPTY
    b0_v39=b0['v39'] if b0 else EMPTY
    b0_v40=b0['v40'] if b0 else EMPTY
    b0_v41=b0['v41'] if b0 else EMPTY
    b0_v42=b0['v42'] if b0 else EMPTY
    b0_v43=b0['v43'] if b0 else EMPTY
    b0_v44=b0['v44'] if b0 else EMPTY
    b0_v45=b0['v45'] if b0 else EMPTY
    b0_v46=b0['v46'] if b0 else EMPTY
    b0_v47=b0['v47'] if b0 else EMPTY
    b0_v48=b0['v48'] if b0 else EMPTY
    b0_v49=b0['v49'] if b0 else EMPTY
    b0_v50=b0['v50'] if b0 else EMPTY
    b0_v51=b0['v51'] if b0 else EMPTY
    b0_v52=b0['v52'] if b0 else EMPTY
    b0_v53=b0['v53'] if b0 else EMPTY
    b0_v54=b0['v54'] if b0 else EMPTY
    b0_v55=b0['v55'] if b0 else EMPTY
    b0_v56=b0['v56'] if b0 else EMPTY
    b0_v57=b0['v57'] if b0 else EMPTY
    b0_v58=b0['v58'] if b0 else EMPTY
    b0_v59=b0['v59'] if b0 else EMPTY
    b0_v60=b0['v60'] if b0 else EMPTY
    b0_v61=b0['v61'] if b0 else EMPTY
    b0_v62=b0['v62'] if b0 else EMPTY
    b0_v63=b0['v63'] if b0 else EMPTY
    b0_v64=b0['v64'] if b0 else EMPTY
    b0_v65=b0['v65'] if b0 else EMPTY
    b0_v66=b0['v66'] if b0 else EMPTY
    b0_v67=b0['v67'] if b0 else EMPTY
    b0_v68=b0['v68'] if b0 else EMPTY
    b0_v69=b0['v69'] if b0 else EMPTY
    b0_v70=b0['v70'] if b0 else EMPTY
    b0_v71=b0['v71'] if b0 else EMPTY
    b0_v72=b0['v72'] if b0 else EMPTY
    b0_v73=b0['v73'] if b0 else EMPTY
    b0_v74=b0['v74'] if b0 else EMPTY
    b0_v75=b0['v75'] if b0 else EMPTY
    b0_v76=b0['v76'] if b0 else EMPTY
    b0_v77=b0['v77'] if b0 else EMPTY
    b0_v78=b0['v78'] if b0 else EMPTY
    b0_v79=b0['v79'] if b0 else EMPTY
    b0_v80=b0['v80'] if b0 else EMPTY
    b0_v81=b0['v81'] if b0 else EMPTY
    b0_v82=b0['v82'] if b0 else EMPTY
    b0_v83=b0['v83'] if b0 else EMPTY
    b0_v84=b0['v84'] if b0 else EMPTY
    b0_v85=b0['v85'] if b0 else EMPTY
    b0_v86=b0['v86'] if b0 else EMPTY
    b0_v87=b0['v87'] if b0 else EMPTY
    b0_v88=b0['v88'] if b0 else EMPTY
    b0_v89=b0['v89'] if b0 else EMPTY
    b0_v90=b0['v90'] if b0 else EMPTY
    b0_v91=b0['v91'] if b0 else EMPTY
    b0_v92=b0['v92'] if b0 else EMPTY
    b0_v93=b0['v93'] if b0 else EMPTY
    b0_v94=b0['v94'] if b0 else EMPTY
    b0_v95=b0['v95'] if b0 else EMPTY
    b0_v96=b0['v96'] if b0 else EMPTY
    b0_v97=b0['v97'] if b0 else EMPTY
    b0_v98=b0['v98'] if b0 else EMPTY
    b0_v99=b0['v99'] if b0 else EMPTY
    a0_ne=a0['ne'] if a0 else EMPTY
    a0_w=a0['form'] if a0 else EMPTY
    a0_lemma=a0['lemma'] if a0 else EMPTY
    a0_t=a0['pos'] if a0 else EMPTY
    a0_dl=a0['rel'] if a0 else EMPTY
    s0_p1_ne=s0['p1']['ne'] if s0 and s0['p1'] else EMPTY
    s0_p1_w=s0['p1']['form'] if s0 and s0['p1'] else EMPTY
    s0_p1_lemma=s0['p1']['lemma'] if s0 and s0['p1'] else EMPTY
    s0_p1_t=s0['p1']['pos'] if s0 and s0['p1'] else EMPTY
    s0_p1_dl=s0['p1']['rel'] if s0 and s0['p1'] else EMPTY
    b0_pathpwd=b0['pathpwd'] if b0 else EMPTY
    b0_apathpwd=b0['apathpwd'] if b0 else EMPTY
    b0_rsb_dl=b0['rsb']['rel'] if b0 and b0['rsb'] else EMPTY
    b0_nswp=b0['nswp'] if b0 else EMPTY
    b0_pathp=b0['pathp'] if b0 else EMPTY
    b0_apathp=b0['apathp'] if b0 else EMPTY
    dist1=abs(s0['id']-b0['id']) if b0 and b0 is not ABT_TOKEN and s0 is not ABT_TOKEN else EMPTY
    if dist1 > 10: dist1=10
    dist2=abs(a0['id']-b0['id']) if b0 and a0 and b0 is not ABT_TOKEN and a0 is not ABT_TOKEN else EMPTY
    if dist2 > 10: dist2=10
    if [s0_ne,tx] != 2*[None]:feats.append('s0_ne&tx=%s_%s_' % (s0_ne,tx))
    if [s0_w,tx] != 2*[None]:feats.append('s0_w&tx=%s_%s_' % (s0_w,tx))
    if [s0_lemma,tx] != 2*[None]:feats.append('s0_lemma&tx=%s_%s_' % (s0_lemma,tx))
    if [s0_t,tx] != 2*[None]:feats.append('s0_t&tx=%s_%s_' % (s0_t,tx))
    if [s0_dl,tx] != 2*[None]:feats.append('s0_dl&tx=%s_%s_' % (s0_dl,tx))
    if [s0_len,tx] != 2*[None]:feats.append('s0_len&tx=%s_%s_' % (s0_len,tx))
    if [s0_v0,tx] != 2*[None]:feats.append('s0_v0&tx=%s_%s_' % (s0_v0,tx))
    if [s0_v1,tx] != 2*[None]:feats.append('s0_v1&tx=%s_%s_' % (s0_v1,tx))
    if [s0_v2,tx] != 2*[None]:feats.append('s0_v2&tx=%s_%s_' % (s0_v2,tx))
    if [s0_v3,tx] != 2*[None]:feats.append('s0_v3&tx=%s_%s_' % (s0_v3,tx))
    if [s0_v4,tx] != 2*[None]:feats.append('s0_v4&tx=%s_%s_' % (s0_v4,tx))
    if [s0_v5,tx] != 2*[None]:feats.append('s0_v5&tx=%s_%s_' % (s0_v5,tx))
    if [s0_v6,tx] != 2*[None]:feats.append('s0_v6&tx=%s_%s_' % (s0_v6,tx))
    if [s0_v7,tx] != 2*[None]:feats.append('s0_v7&tx=%s_%s_' % (s0_v7,tx))
    if [s0_v8,tx] != 2*[None]:feats.append('s0_v8&tx=%s_%s_' % (s0_v8,tx))
    if [s0_v9,tx] != 2*[None]:feats.append('s0_v9&tx=%s_%s_' % (s0_v9,tx))
    if [s0_v10,tx] != 2*[None]:feats.append('s0_v10&tx=%s_%s_' % (s0_v10,tx))
    if [s0_v11,tx] != 2*[None]:feats.append('s0_v11&tx=%s_%s_' % (s0_v11,tx))
    if [s0_v12,tx] != 2*[None]:feats.append('s0_v12&tx=%s_%s_' % (s0_v12,tx))
    if [s0_v13,tx] != 2*[None]:feats.append('s0_v13&tx=%s_%s_' % (s0_v13,tx))
    if [s0_v14,tx] != 2*[None]:feats.append('s0_v14&tx=%s_%s_' % (s0_v14,tx))
    if [s0_v15,tx] != 2*[None]:feats.append('s0_v15&tx=%s_%s_' % (s0_v15,tx))
    if [s0_v16,tx] != 2*[None]:feats.append('s0_v16&tx=%s_%s_' % (s0_v16,tx))
    if [s0_v17,tx] != 2*[None]:feats.append('s0_v17&tx=%s_%s_' % (s0_v17,tx))
    if [s0_v18,tx] != 2*[None]:feats.append('s0_v18&tx=%s_%s_' % (s0_v18,tx))
    if [s0_v19,tx] != 2*[None]:feats.append('s0_v19&tx=%s_%s_' % (s0_v19,tx))
    if [s0_v20,tx] != 2*[None]:feats.append('s0_v20&tx=%s_%s_' % (s0_v20,tx))
    if [s0_v21,tx] != 2*[None]:feats.append('s0_v21&tx=%s_%s_' % (s0_v21,tx))
    if [s0_v22,tx] != 2*[None]:feats.append('s0_v22&tx=%s_%s_' % (s0_v22,tx))
    if [s0_v23,tx] != 2*[None]:feats.append('s0_v23&tx=%s_%s_' % (s0_v23,tx))
    if [s0_v24,tx] != 2*[None]:feats.append('s0_v24&tx=%s_%s_' % (s0_v24,tx))
    if [s0_v25,tx] != 2*[None]:feats.append('s0_v25&tx=%s_%s_' % (s0_v25,tx))
    if [s0_v26,tx] != 2*[None]:feats.append('s0_v26&tx=%s_%s_' % (s0_v26,tx))
    if [s0_v27,tx] != 2*[None]:feats.append('s0_v27&tx=%s_%s_' % (s0_v27,tx))
    if [s0_v28,tx] != 2*[None]:feats.append('s0_v28&tx=%s_%s_' % (s0_v28,tx))
    if [s0_v29,tx] != 2*[None]:feats.append('s0_v29&tx=%s_%s_' % (s0_v29,tx))
    if [s0_v30,tx] != 2*[None]:feats.append('s0_v30&tx=%s_%s_' % (s0_v30,tx))
    if [s0_v31,tx] != 2*[None]:feats.append('s0_v31&tx=%s_%s_' % (s0_v31,tx))
    if [s0_v32,tx] != 2*[None]:feats.append('s0_v32&tx=%s_%s_' % (s0_v32,tx))
    if [s0_v33,tx] != 2*[None]:feats.append('s0_v33&tx=%s_%s_' % (s0_v33,tx))
    if [s0_v34,tx] != 2*[None]:feats.append('s0_v34&tx=%s_%s_' % (s0_v34,tx))
    if [s0_v35,tx] != 2*[None]:feats.append('s0_v35&tx=%s_%s_' % (s0_v35,tx))
    if [s0_v36,tx] != 2*[None]:feats.append('s0_v36&tx=%s_%s_' % (s0_v36,tx))
    if [s0_v37,tx] != 2*[None]:feats.append('s0_v37&tx=%s_%s_' % (s0_v37,tx))
    if [s0_v38,tx] != 2*[None]:feats.append('s0_v38&tx=%s_%s_' % (s0_v38,tx))
    if [s0_v39,tx] != 2*[None]:feats.append('s0_v39&tx=%s_%s_' % (s0_v39,tx))
    if [s0_v40,tx] != 2*[None]:feats.append('s0_v40&tx=%s_%s_' % (s0_v40,tx))
    if [s0_v41,tx] != 2*[None]:feats.append('s0_v41&tx=%s_%s_' % (s0_v41,tx))
    if [s0_v42,tx] != 2*[None]:feats.append('s0_v42&tx=%s_%s_' % (s0_v42,tx))
    if [s0_v43,tx] != 2*[None]:feats.append('s0_v43&tx=%s_%s_' % (s0_v43,tx))
    if [s0_v44,tx] != 2*[None]:feats.append('s0_v44&tx=%s_%s_' % (s0_v44,tx))
    if [s0_v45,tx] != 2*[None]:feats.append('s0_v45&tx=%s_%s_' % (s0_v45,tx))
    if [s0_v46,tx] != 2*[None]:feats.append('s0_v46&tx=%s_%s_' % (s0_v46,tx))
    if [s0_v47,tx] != 2*[None]:feats.append('s0_v47&tx=%s_%s_' % (s0_v47,tx))
    if [s0_v48,tx] != 2*[None]:feats.append('s0_v48&tx=%s_%s_' % (s0_v48,tx))
    if [s0_v49,tx] != 2*[None]:feats.append('s0_v49&tx=%s_%s_' % (s0_v49,tx))
    if [s0_v50,tx] != 2*[None]:feats.append('s0_v50&tx=%s_%s_' % (s0_v50,tx))
    if [s0_v51,tx] != 2*[None]:feats.append('s0_v51&tx=%s_%s_' % (s0_v51,tx))
    if [s0_v52,tx] != 2*[None]:feats.append('s0_v52&tx=%s_%s_' % (s0_v52,tx))
    if [s0_v53,tx] != 2*[None]:feats.append('s0_v53&tx=%s_%s_' % (s0_v53,tx))
    if [s0_v54,tx] != 2*[None]:feats.append('s0_v54&tx=%s_%s_' % (s0_v54,tx))
    if [s0_v55,tx] != 2*[None]:feats.append('s0_v55&tx=%s_%s_' % (s0_v55,tx))
    if [s0_v56,tx] != 2*[None]:feats.append('s0_v56&tx=%s_%s_' % (s0_v56,tx))
    if [s0_v57,tx] != 2*[None]:feats.append('s0_v57&tx=%s_%s_' % (s0_v57,tx))
    if [s0_v58,tx] != 2*[None]:feats.append('s0_v58&tx=%s_%s_' % (s0_v58,tx))
    if [s0_v59,tx] != 2*[None]:feats.append('s0_v59&tx=%s_%s_' % (s0_v59,tx))
    if [s0_v60,tx] != 2*[None]:feats.append('s0_v60&tx=%s_%s_' % (s0_v60,tx))
    if [s0_v61,tx] != 2*[None]:feats.append('s0_v61&tx=%s_%s_' % (s0_v61,tx))
    if [s0_v62,tx] != 2*[None]:feats.append('s0_v62&tx=%s_%s_' % (s0_v62,tx))
    if [s0_v63,tx] != 2*[None]:feats.append('s0_v63&tx=%s_%s_' % (s0_v63,tx))
    if [s0_v64,tx] != 2*[None]:feats.append('s0_v64&tx=%s_%s_' % (s0_v64,tx))
    if [s0_v65,tx] != 2*[None]:feats.append('s0_v65&tx=%s_%s_' % (s0_v65,tx))
    if [s0_v66,tx] != 2*[None]:feats.append('s0_v66&tx=%s_%s_' % (s0_v66,tx))
    if [s0_v67,tx] != 2*[None]:feats.append('s0_v67&tx=%s_%s_' % (s0_v67,tx))
    if [s0_v68,tx] != 2*[None]:feats.append('s0_v68&tx=%s_%s_' % (s0_v68,tx))
    if [s0_v69,tx] != 2*[None]:feats.append('s0_v69&tx=%s_%s_' % (s0_v69,tx))
    if [s0_v70,tx] != 2*[None]:feats.append('s0_v70&tx=%s_%s_' % (s0_v70,tx))
    if [s0_v71,tx] != 2*[None]:feats.append('s0_v71&tx=%s_%s_' % (s0_v71,tx))
    if [s0_v72,tx] != 2*[None]:feats.append('s0_v72&tx=%s_%s_' % (s0_v72,tx))
    if [s0_v73,tx] != 2*[None]:feats.append('s0_v73&tx=%s_%s_' % (s0_v73,tx))
    if [s0_v74,tx] != 2*[None]:feats.append('s0_v74&tx=%s_%s_' % (s0_v74,tx))
    if [s0_v75,tx] != 2*[None]:feats.append('s0_v75&tx=%s_%s_' % (s0_v75,tx))
    if [s0_v76,tx] != 2*[None]:feats.append('s0_v76&tx=%s_%s_' % (s0_v76,tx))
    if [s0_v77,tx] != 2*[None]:feats.append('s0_v77&tx=%s_%s_' % (s0_v77,tx))
    if [s0_v78,tx] != 2*[None]:feats.append('s0_v78&tx=%s_%s_' % (s0_v78,tx))
    if [s0_v79,tx] != 2*[None]:feats.append('s0_v79&tx=%s_%s_' % (s0_v79,tx))
    if [s0_v80,tx] != 2*[None]:feats.append('s0_v80&tx=%s_%s_' % (s0_v80,tx))
    if [s0_v81,tx] != 2*[None]:feats.append('s0_v81&tx=%s_%s_' % (s0_v81,tx))
    if [s0_v82,tx] != 2*[None]:feats.append('s0_v82&tx=%s_%s_' % (s0_v82,tx))
    if [s0_v83,tx] != 2*[None]:feats.append('s0_v83&tx=%s_%s_' % (s0_v83,tx))
    if [s0_v84,tx] != 2*[None]:feats.append('s0_v84&tx=%s_%s_' % (s0_v84,tx))
    if [s0_v85,tx] != 2*[None]:feats.append('s0_v85&tx=%s_%s_' % (s0_v85,tx))
    if [s0_v86,tx] != 2*[None]:feats.append('s0_v86&tx=%s_%s_' % (s0_v86,tx))
    if [s0_v87,tx] != 2*[None]:feats.append('s0_v87&tx=%s_%s_' % (s0_v87,tx))
    if [s0_v88,tx] != 2*[None]:feats.append('s0_v88&tx=%s_%s_' % (s0_v88,tx))
    if [s0_v89,tx] != 2*[None]:feats.append('s0_v89&tx=%s_%s_' % (s0_v89,tx))
    if [s0_v90,tx] != 2*[None]:feats.append('s0_v90&tx=%s_%s_' % (s0_v90,tx))
    if [s0_v91,tx] != 2*[None]:feats.append('s0_v91&tx=%s_%s_' % (s0_v91,tx))
    if [s0_v92,tx] != 2*[None]:feats.append('s0_v92&tx=%s_%s_' % (s0_v92,tx))
    if [s0_v93,tx] != 2*[None]:feats.append('s0_v93&tx=%s_%s_' % (s0_v93,tx))
    if [s0_v94,tx] != 2*[None]:feats.append('s0_v94&tx=%s_%s_' % (s0_v94,tx))
    if [s0_v95,tx] != 2*[None]:feats.append('s0_v95&tx=%s_%s_' % (s0_v95,tx))
    if [s0_v96,tx] != 2*[None]:feats.append('s0_v96&tx=%s_%s_' % (s0_v96,tx))
    if [s0_v97,tx] != 2*[None]:feats.append('s0_v97&tx=%s_%s_' % (s0_v97,tx))
    if [s0_v98,tx] != 2*[None]:feats.append('s0_v98&tx=%s_%s_' % (s0_v98,tx))
    if [s0_v99,tx] != 2*[None]:feats.append('s0_v99&tx=%s_%s_' % (s0_v99,tx))
    if [s0_v0] != 1*[None]:feats.append('s0_v0=%s_' % (s0_v0))
    if [s0_v1] != 1*[None]:feats.append('s0_v1=%s_' % (s0_v1))
    if [s0_v2] != 1*[None]:feats.append('s0_v2=%s_' % (s0_v2))
    if [s0_v3] != 1*[None]:feats.append('s0_v3=%s_' % (s0_v3))
    if [s0_v4] != 1*[None]:feats.append('s0_v4=%s_' % (s0_v4))
    if [s0_v5] != 1*[None]:feats.append('s0_v5=%s_' % (s0_v5))
    if [s0_v6] != 1*[None]:feats.append('s0_v6=%s_' % (s0_v6))
    if [s0_v7] != 1*[None]:feats.append('s0_v7=%s_' % (s0_v7))
    if [s0_v8] != 1*[None]:feats.append('s0_v8=%s_' % (s0_v8))
    if [s0_v9] != 1*[None]:feats.append('s0_v9=%s_' % (s0_v9))
    if [s0_v10] != 1*[None]:feats.append('s0_v10=%s_' % (s0_v10))
    if [s0_v11] != 1*[None]:feats.append('s0_v11=%s_' % (s0_v11))
    if [s0_v12] != 1*[None]:feats.append('s0_v12=%s_' % (s0_v12))
    if [s0_v13] != 1*[None]:feats.append('s0_v13=%s_' % (s0_v13))
    if [s0_v14] != 1*[None]:feats.append('s0_v14=%s_' % (s0_v14))
    if [s0_v15] != 1*[None]:feats.append('s0_v15=%s_' % (s0_v15))
    if [s0_v16] != 1*[None]:feats.append('s0_v16=%s_' % (s0_v16))
    if [s0_v17] != 1*[None]:feats.append('s0_v17=%s_' % (s0_v17))
    if [s0_v18] != 1*[None]:feats.append('s0_v18=%s_' % (s0_v18))
    if [s0_v19] != 1*[None]:feats.append('s0_v19=%s_' % (s0_v19))
    if [s0_v20] != 1*[None]:feats.append('s0_v20=%s_' % (s0_v20))
    if [s0_v21] != 1*[None]:feats.append('s0_v21=%s_' % (s0_v21))
    if [s0_v22] != 1*[None]:feats.append('s0_v22=%s_' % (s0_v22))
    if [s0_v23] != 1*[None]:feats.append('s0_v23=%s_' % (s0_v23))
    if [s0_v24] != 1*[None]:feats.append('s0_v24=%s_' % (s0_v24))
    if [s0_v25] != 1*[None]:feats.append('s0_v25=%s_' % (s0_v25))
    if [s0_v26] != 1*[None]:feats.append('s0_v26=%s_' % (s0_v26))
    if [s0_v27] != 1*[None]:feats.append('s0_v27=%s_' % (s0_v27))
    if [s0_v28] != 1*[None]:feats.append('s0_v28=%s_' % (s0_v28))
    if [s0_v29] != 1*[None]:feats.append('s0_v29=%s_' % (s0_v29))
    if [s0_v30] != 1*[None]:feats.append('s0_v30=%s_' % (s0_v30))
    if [s0_v31] != 1*[None]:feats.append('s0_v31=%s_' % (s0_v31))
    if [s0_v32] != 1*[None]:feats.append('s0_v32=%s_' % (s0_v32))
    if [s0_v33] != 1*[None]:feats.append('s0_v33=%s_' % (s0_v33))
    if [s0_v34] != 1*[None]:feats.append('s0_v34=%s_' % (s0_v34))
    if [s0_v35] != 1*[None]:feats.append('s0_v35=%s_' % (s0_v35))
    if [s0_v36] != 1*[None]:feats.append('s0_v36=%s_' % (s0_v36))
    if [s0_v37] != 1*[None]:feats.append('s0_v37=%s_' % (s0_v37))
    if [s0_v38] != 1*[None]:feats.append('s0_v38=%s_' % (s0_v38))
    if [s0_v39] != 1*[None]:feats.append('s0_v39=%s_' % (s0_v39))
    if [s0_v40] != 1*[None]:feats.append('s0_v40=%s_' % (s0_v40))
    if [s0_v41] != 1*[None]:feats.append('s0_v41=%s_' % (s0_v41))
    if [s0_v42] != 1*[None]:feats.append('s0_v42=%s_' % (s0_v42))
    if [s0_v43] != 1*[None]:feats.append('s0_v43=%s_' % (s0_v43))
    if [s0_v44] != 1*[None]:feats.append('s0_v44=%s_' % (s0_v44))
    if [s0_v45] != 1*[None]:feats.append('s0_v45=%s_' % (s0_v45))
    if [s0_v46] != 1*[None]:feats.append('s0_v46=%s_' % (s0_v46))
    if [s0_v47] != 1*[None]:feats.append('s0_v47=%s_' % (s0_v47))
    if [s0_v48] != 1*[None]:feats.append('s0_v48=%s_' % (s0_v48))
    if [s0_v49] != 1*[None]:feats.append('s0_v49=%s_' % (s0_v49))
    if [s0_v50] != 1*[None]:feats.append('s0_v50=%s_' % (s0_v50))
    if [s0_v51] != 1*[None]:feats.append('s0_v51=%s_' % (s0_v51))
    if [s0_v52] != 1*[None]:feats.append('s0_v52=%s_' % (s0_v52))
    if [s0_v53] != 1*[None]:feats.append('s0_v53=%s_' % (s0_v53))
    if [s0_v54] != 1*[None]:feats.append('s0_v54=%s_' % (s0_v54))
    if [s0_v55] != 1*[None]:feats.append('s0_v55=%s_' % (s0_v55))
    if [s0_v56] != 1*[None]:feats.append('s0_v56=%s_' % (s0_v56))
    if [s0_v57] != 1*[None]:feats.append('s0_v57=%s_' % (s0_v57))
    if [s0_v58] != 1*[None]:feats.append('s0_v58=%s_' % (s0_v58))
    if [s0_v59] != 1*[None]:feats.append('s0_v59=%s_' % (s0_v59))
    if [s0_v60] != 1*[None]:feats.append('s0_v60=%s_' % (s0_v60))
    if [s0_v61] != 1*[None]:feats.append('s0_v61=%s_' % (s0_v61))
    if [s0_v62] != 1*[None]:feats.append('s0_v62=%s_' % (s0_v62))
    if [s0_v63] != 1*[None]:feats.append('s0_v63=%s_' % (s0_v63))
    if [s0_v64] != 1*[None]:feats.append('s0_v64=%s_' % (s0_v64))
    if [s0_v65] != 1*[None]:feats.append('s0_v65=%s_' % (s0_v65))
    if [s0_v66] != 1*[None]:feats.append('s0_v66=%s_' % (s0_v66))
    if [s0_v67] != 1*[None]:feats.append('s0_v67=%s_' % (s0_v67))
    if [s0_v68] != 1*[None]:feats.append('s0_v68=%s_' % (s0_v68))
    if [s0_v69] != 1*[None]:feats.append('s0_v69=%s_' % (s0_v69))
    if [s0_v70] != 1*[None]:feats.append('s0_v70=%s_' % (s0_v70))
    if [s0_v71] != 1*[None]:feats.append('s0_v71=%s_' % (s0_v71))
    if [s0_v72] != 1*[None]:feats.append('s0_v72=%s_' % (s0_v72))
    if [s0_v73] != 1*[None]:feats.append('s0_v73=%s_' % (s0_v73))
    if [s0_v74] != 1*[None]:feats.append('s0_v74=%s_' % (s0_v74))
    if [s0_v75] != 1*[None]:feats.append('s0_v75=%s_' % (s0_v75))
    if [s0_v76] != 1*[None]:feats.append('s0_v76=%s_' % (s0_v76))
    if [s0_v77] != 1*[None]:feats.append('s0_v77=%s_' % (s0_v77))
    if [s0_v78] != 1*[None]:feats.append('s0_v78=%s_' % (s0_v78))
    if [s0_v79] != 1*[None]:feats.append('s0_v79=%s_' % (s0_v79))
    if [s0_v80] != 1*[None]:feats.append('s0_v80=%s_' % (s0_v80))
    if [s0_v81] != 1*[None]:feats.append('s0_v81=%s_' % (s0_v81))
    if [s0_v82] != 1*[None]:feats.append('s0_v82=%s_' % (s0_v82))
    if [s0_v83] != 1*[None]:feats.append('s0_v83=%s_' % (s0_v83))
    if [s0_v84] != 1*[None]:feats.append('s0_v84=%s_' % (s0_v84))
    if [s0_v85] != 1*[None]:feats.append('s0_v85=%s_' % (s0_v85))
    if [s0_v86] != 1*[None]:feats.append('s0_v86=%s_' % (s0_v86))
    if [s0_v87] != 1*[None]:feats.append('s0_v87=%s_' % (s0_v87))
    if [s0_v88] != 1*[None]:feats.append('s0_v88=%s_' % (s0_v88))
    if [s0_v89] != 1*[None]:feats.append('s0_v89=%s_' % (s0_v89))
    if [s0_v90] != 1*[None]:feats.append('s0_v90=%s_' % (s0_v90))
    if [s0_v91] != 1*[None]:feats.append('s0_v91=%s_' % (s0_v91))
    if [s0_v92] != 1*[None]:feats.append('s0_v92=%s_' % (s0_v92))
    if [s0_v93] != 1*[None]:feats.append('s0_v93=%s_' % (s0_v93))
    if [s0_v94] != 1*[None]:feats.append('s0_v94=%s_' % (s0_v94))
    if [s0_v95] != 1*[None]:feats.append('s0_v95=%s_' % (s0_v95))
    if [s0_v96] != 1*[None]:feats.append('s0_v96=%s_' % (s0_v96))
    if [s0_v97] != 1*[None]:feats.append('s0_v97=%s_' % (s0_v97))
    if [s0_v98] != 1*[None]:feats.append('s0_v98=%s_' % (s0_v98))
    if [s0_v99] != 1*[None]:feats.append('s0_v99=%s_' % (s0_v99))
    if [b0_ne] != 1*[None]:feats.append('b0_ne=%s_' % (b0_ne))
    if [b0_w] != 1*[None]:feats.append('b0_w=%s_' % (b0_w))
    if [b0_lemma] != 1*[None]:feats.append('b0_lemma=%s_' % (b0_lemma))
    if [b0_t] != 1*[None]:feats.append('b0_t=%s_' % (b0_t))
    if [b0_dl] != 1*[None]:feats.append('b0_dl=%s_' % (b0_dl))
    if [b0_len] != 1*[None]:feats.append('b0_len=%s_' % (b0_len))
    if [b0_reph] != 1*[None]:feats.append('b0_reph=%s_' % (b0_reph))
    if [b0_v0] != 1*[None]:feats.append('b0_v0=%s_' % (b0_v0))
    if [b0_v1] != 1*[None]:feats.append('b0_v1=%s_' % (b0_v1))
    if [b0_v2] != 1*[None]:feats.append('b0_v2=%s_' % (b0_v2))
    if [b0_v3] != 1*[None]:feats.append('b0_v3=%s_' % (b0_v3))
    if [b0_v4] != 1*[None]:feats.append('b0_v4=%s_' % (b0_v4))
    if [b0_v5] != 1*[None]:feats.append('b0_v5=%s_' % (b0_v5))
    if [b0_v6] != 1*[None]:feats.append('b0_v6=%s_' % (b0_v6))
    if [b0_v7] != 1*[None]:feats.append('b0_v7=%s_' % (b0_v7))
    if [b0_v8] != 1*[None]:feats.append('b0_v8=%s_' % (b0_v8))
    if [b0_v9] != 1*[None]:feats.append('b0_v9=%s_' % (b0_v9))
    if [b0_v10] != 1*[None]:feats.append('b0_v10=%s_' % (b0_v10))
    if [b0_v11] != 1*[None]:feats.append('b0_v11=%s_' % (b0_v11))
    if [b0_v12] != 1*[None]:feats.append('b0_v12=%s_' % (b0_v12))
    if [b0_v13] != 1*[None]:feats.append('b0_v13=%s_' % (b0_v13))
    if [b0_v14] != 1*[None]:feats.append('b0_v14=%s_' % (b0_v14))
    if [b0_v15] != 1*[None]:feats.append('b0_v15=%s_' % (b0_v15))
    if [b0_v16] != 1*[None]:feats.append('b0_v16=%s_' % (b0_v16))
    if [b0_v17] != 1*[None]:feats.append('b0_v17=%s_' % (b0_v17))
    if [b0_v18] != 1*[None]:feats.append('b0_v18=%s_' % (b0_v18))
    if [b0_v19] != 1*[None]:feats.append('b0_v19=%s_' % (b0_v19))
    if [b0_v20] != 1*[None]:feats.append('b0_v20=%s_' % (b0_v20))
    if [b0_v21] != 1*[None]:feats.append('b0_v21=%s_' % (b0_v21))
    if [b0_v22] != 1*[None]:feats.append('b0_v22=%s_' % (b0_v22))
    if [b0_v23] != 1*[None]:feats.append('b0_v23=%s_' % (b0_v23))
    if [b0_v24] != 1*[None]:feats.append('b0_v24=%s_' % (b0_v24))
    if [b0_v25] != 1*[None]:feats.append('b0_v25=%s_' % (b0_v25))
    if [b0_v26] != 1*[None]:feats.append('b0_v26=%s_' % (b0_v26))
    if [b0_v27] != 1*[None]:feats.append('b0_v27=%s_' % (b0_v27))
    if [b0_v28] != 1*[None]:feats.append('b0_v28=%s_' % (b0_v28))
    if [b0_v29] != 1*[None]:feats.append('b0_v29=%s_' % (b0_v29))
    if [b0_v30] != 1*[None]:feats.append('b0_v30=%s_' % (b0_v30))
    if [b0_v31] != 1*[None]:feats.append('b0_v31=%s_' % (b0_v31))
    if [b0_v32] != 1*[None]:feats.append('b0_v32=%s_' % (b0_v32))
    if [b0_v33] != 1*[None]:feats.append('b0_v33=%s_' % (b0_v33))
    if [b0_v34] != 1*[None]:feats.append('b0_v34=%s_' % (b0_v34))
    if [b0_v35] != 1*[None]:feats.append('b0_v35=%s_' % (b0_v35))
    if [b0_v36] != 1*[None]:feats.append('b0_v36=%s_' % (b0_v36))
    if [b0_v37] != 1*[None]:feats.append('b0_v37=%s_' % (b0_v37))
    if [b0_v38] != 1*[None]:feats.append('b0_v38=%s_' % (b0_v38))
    if [b0_v39] != 1*[None]:feats.append('b0_v39=%s_' % (b0_v39))
    if [b0_v40] != 1*[None]:feats.append('b0_v40=%s_' % (b0_v40))
    if [b0_v41] != 1*[None]:feats.append('b0_v41=%s_' % (b0_v41))
    if [b0_v42] != 1*[None]:feats.append('b0_v42=%s_' % (b0_v42))
    if [b0_v43] != 1*[None]:feats.append('b0_v43=%s_' % (b0_v43))
    if [b0_v44] != 1*[None]:feats.append('b0_v44=%s_' % (b0_v44))
    if [b0_v45] != 1*[None]:feats.append('b0_v45=%s_' % (b0_v45))
    if [b0_v46] != 1*[None]:feats.append('b0_v46=%s_' % (b0_v46))
    if [b0_v47] != 1*[None]:feats.append('b0_v47=%s_' % (b0_v47))
    if [b0_v48] != 1*[None]:feats.append('b0_v48=%s_' % (b0_v48))
    if [b0_v49] != 1*[None]:feats.append('b0_v49=%s_' % (b0_v49))
    if [b0_v50] != 1*[None]:feats.append('b0_v50=%s_' % (b0_v50))
    if [b0_v51] != 1*[None]:feats.append('b0_v51=%s_' % (b0_v51))
    if [b0_v52] != 1*[None]:feats.append('b0_v52=%s_' % (b0_v52))
    if [b0_v53] != 1*[None]:feats.append('b0_v53=%s_' % (b0_v53))
    if [b0_v54] != 1*[None]:feats.append('b0_v54=%s_' % (b0_v54))
    if [b0_v55] != 1*[None]:feats.append('b0_v55=%s_' % (b0_v55))
    if [b0_v56] != 1*[None]:feats.append('b0_v56=%s_' % (b0_v56))
    if [b0_v57] != 1*[None]:feats.append('b0_v57=%s_' % (b0_v57))
    if [b0_v58] != 1*[None]:feats.append('b0_v58=%s_' % (b0_v58))
    if [b0_v59] != 1*[None]:feats.append('b0_v59=%s_' % (b0_v59))
    if [b0_v60] != 1*[None]:feats.append('b0_v60=%s_' % (b0_v60))
    if [b0_v61] != 1*[None]:feats.append('b0_v61=%s_' % (b0_v61))
    if [b0_v62] != 1*[None]:feats.append('b0_v62=%s_' % (b0_v62))
    if [b0_v63] != 1*[None]:feats.append('b0_v63=%s_' % (b0_v63))
    if [b0_v64] != 1*[None]:feats.append('b0_v64=%s_' % (b0_v64))
    if [b0_v65] != 1*[None]:feats.append('b0_v65=%s_' % (b0_v65))
    if [b0_v66] != 1*[None]:feats.append('b0_v66=%s_' % (b0_v66))
    if [b0_v67] != 1*[None]:feats.append('b0_v67=%s_' % (b0_v67))
    if [b0_v68] != 1*[None]:feats.append('b0_v68=%s_' % (b0_v68))
    if [b0_v69] != 1*[None]:feats.append('b0_v69=%s_' % (b0_v69))
    if [b0_v70] != 1*[None]:feats.append('b0_v70=%s_' % (b0_v70))
    if [b0_v71] != 1*[None]:feats.append('b0_v71=%s_' % (b0_v71))
    if [b0_v72] != 1*[None]:feats.append('b0_v72=%s_' % (b0_v72))
    if [b0_v73] != 1*[None]:feats.append('b0_v73=%s_' % (b0_v73))
    if [b0_v74] != 1*[None]:feats.append('b0_v74=%s_' % (b0_v74))
    if [b0_v75] != 1*[None]:feats.append('b0_v75=%s_' % (b0_v75))
    if [b0_v76] != 1*[None]:feats.append('b0_v76=%s_' % (b0_v76))
    if [b0_v77] != 1*[None]:feats.append('b0_v77=%s_' % (b0_v77))
    if [b0_v78] != 1*[None]:feats.append('b0_v78=%s_' % (b0_v78))
    if [b0_v79] != 1*[None]:feats.append('b0_v79=%s_' % (b0_v79))
    if [b0_v80] != 1*[None]:feats.append('b0_v80=%s_' % (b0_v80))
    if [b0_v81] != 1*[None]:feats.append('b0_v81=%s_' % (b0_v81))
    if [b0_v82] != 1*[None]:feats.append('b0_v82=%s_' % (b0_v82))
    if [b0_v83] != 1*[None]:feats.append('b0_v83=%s_' % (b0_v83))
    if [b0_v84] != 1*[None]:feats.append('b0_v84=%s_' % (b0_v84))
    if [b0_v85] != 1*[None]:feats.append('b0_v85=%s_' % (b0_v85))
    if [b0_v86] != 1*[None]:feats.append('b0_v86=%s_' % (b0_v86))
    if [b0_v87] != 1*[None]:feats.append('b0_v87=%s_' % (b0_v87))
    if [b0_v88] != 1*[None]:feats.append('b0_v88=%s_' % (b0_v88))
    if [b0_v89] != 1*[None]:feats.append('b0_v89=%s_' % (b0_v89))
    if [b0_v90] != 1*[None]:feats.append('b0_v90=%s_' % (b0_v90))
    if [b0_v91] != 1*[None]:feats.append('b0_v91=%s_' % (b0_v91))
    if [b0_v92] != 1*[None]:feats.append('b0_v92=%s_' % (b0_v92))
    if [b0_v93] != 1*[None]:feats.append('b0_v93=%s_' % (b0_v93))
    if [b0_v94] != 1*[None]:feats.append('b0_v94=%s_' % (b0_v94))
    if [b0_v95] != 1*[None]:feats.append('b0_v95=%s_' % (b0_v95))
    if [b0_v96] != 1*[None]:feats.append('b0_v96=%s_' % (b0_v96))
    if [b0_v97] != 1*[None]:feats.append('b0_v97=%s_' % (b0_v97))
    if [b0_v98] != 1*[None]:feats.append('b0_v98=%s_' % (b0_v98))
    if [b0_v99] != 1*[None]:feats.append('b0_v99=%s_' % (b0_v99))
    if [a0_ne] != 1*[None]:feats.append('a0_ne=%s_' % (a0_ne))
    if [a0_w] != 1*[None]:feats.append('a0_w=%s_' % (a0_w))
    if [a0_lemma] != 1*[None]:feats.append('a0_lemma=%s_' % (a0_lemma))
    if [a0_t] != 1*[None]:feats.append('a0_t=%s_' % (a0_t))
    if [a0_dl] != 1*[None]:feats.append('a0_dl=%s_' % (a0_dl))
    if [s0_p1_ne] != 1*[None]:feats.append('s0_p1_ne=%s_' % (s0_p1_ne))
    if [s0_p1_w] != 1*[None]:feats.append('s0_p1_w=%s_' % (s0_p1_w))
    if [s0_p1_lemma] != 1*[None]:feats.append('s0_p1_lemma=%s_' % (s0_p1_lemma))
    if [s0_p1_t] != 1*[None]:feats.append('s0_p1_t=%s_' % (s0_p1_t))
    if [s0_p1_dl] != 1*[None]:feats.append('s0_p1_dl=%s_' % (s0_p1_dl))
    if [b0_pathpwd,b0_lemma,s0_lemma] != 3*[None]:feats.append('b0_pathpwd&b0_lemma&s0_lemma=%s_%s_%s_' % (b0_pathpwd,b0_lemma,s0_lemma))
    if [b0_apathpwd,a0_lemma,b0_lemma] != 3*[None]:feats.append('b0_apathpwd&a0_lemma&b0_lemma=%s_%s_%s_' % (b0_apathpwd,a0_lemma,b0_lemma))
    if [b0_lemma,b0_rsb_dl] != 2*[None]:feats.append('b0_lemma&b0_rsb_dl=%s_%s_' % (b0_lemma,b0_rsb_dl))
    if [b0_lemma,b0_nswp] != 2*[None]:feats.append('b0_lemma&b0_nswp=%s_%s_' % (b0_lemma,b0_nswp))
    if [dist1] != 1*[None]:feats.append('dist1=%s_' % (dist1))
    if [dist1,b0_pathp] != 2*[None]:feats.append('dist1&b0_pathp=%s_%s_' % (dist1,b0_pathp))
    if [dist2] != 1*[None]:feats.append('dist2=%s_' % (dist2))
    if [dist2,b0_apathp] != 2*[None]:feats.append('dist2&b0_apathp=%s_%s_' % (dist2,b0_apathp))
    if [s0_lemma,b0_t] != 2*[None]:feats.append('s0_lemma&b0_t=%s_%s_' % (s0_lemma,b0_t))
    if [s0_lemma,b0_dl] != 2*[None]:feats.append('s0_lemma&b0_dl=%s_%s_' % (s0_lemma,b0_dl))
    if [s0_t,b0_lemma] != 2*[None]:feats.append('s0_t&b0_lemma=%s_%s_' % (s0_t,b0_lemma))
    if [s0_dl,b0_lemma] != 2*[None]:feats.append('s0_dl&b0_lemma=%s_%s_' % (s0_dl,b0_lemma))
    if [s0_ne,b0_ne] != 2*[None]:feats.append('s0_ne&b0_ne=%s_%s_' % (s0_ne,b0_ne))
    if [a0_t,b0_lemma] != 2*[None]:feats.append('a0_t&b0_lemma=%s_%s_' % (a0_t,b0_lemma))
    if [a0_dl,b0_lemma] != 2*[None]:feats.append('a0_dl&b0_lemma=%s_%s_' % (a0_dl,b0_lemma))
    if [a0_ne,b0_ne] != 2*[None]:feats.append('a0_ne&b0_ne=%s_%s_' % (a0_ne,b0_ne))
    return feats